### ISSUE TITLE
Fix Counting in Docs

### ISSUE THREAD

**Issue by Ione15** [fosscord/fosscord-docs#3]
https://docs.fosscord.com/contributing/ here is a mistake at the mongodb guide where it does say 1. 1. 1. 1. instead of 1. 2. 3. 4.

**Comment by Flam3rboy** [comment]
I think this is a problem with mkdocs, @Stylix58 can you have a look

**Comment by Stylix58** [comment]
I will see.

**Comment by Stylix58** [comment]
Ok, I don't know how to fix this...

**Comment by Stylix58** [comment]
I have founded how to solve the issue!
https://stackoverflow.com/a/57525812

**Comment by Stylix58** [comment]
Fixed by commit 5440405dc12a61f55358cc2dbf2d3932addc80f0!
